backend:
  name: github
  repo: mail-drafts7/knowledgepack_docsify_setup  # Your GitHub repo
  branch: main                       # Main branch
  
# Enable editorial workflow for content review
publish_mode: editorial_workflow

media_folder: "docs/assets"           # Where uploaded media files go
public_folder: "/assets"

media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

# Enable local development support
local_backend: true

# Site configuration - GitHub Pages URL
site_url: https://mail-drafts7.github.io/knowledgepack_docsify_setup
display_url: https://mail-drafts7.github.io/knowledgepack_docsify_setup

# Editor configuration
editor:
  preview: true

collections:
  - name: "docs"
    label: "Documentation"
    folder: "docs"                    # Folder where Markdown files are stored
    create: true                     # Allows creating new files
    slug: "{{slug}}"
    extension: "md"
    fields:
      - { label: "Title", name: "title", widget: "string", required: false }
      - { label: "Body", name: "body", widget: "markdown" }
  - name: "navigation"
    label: "Site Navigation"
    files:
      - name: "sidebar"
        label: "Sidebar Navigation"
        file: "docs/_sidebar.md"
        fields:
          - { label: "Navigation Menu", name: "body", widget: "markdown", hint: "Edit the navigation menu. Use format: - [Page Name](filename.md)" }
