# Backend configuration - Local proxy for development
backend:
  name: git-gateway
  branch: main

# Site configuration
site_name: "Knowledge Pack CMS"
app_name: "Knowledge Pack CMS"

# Simple publish mode for local development
publish_mode: simple

# Media files stored locally
media_folder: "docs/assets"
public_folder: "/assets"

# Local development support (enabled for local proxy)
local_backend: true

# Editorial workflow settings
show_preview_links: true

# Site URLs - GitHub Pages hosting
site_url: https://mail-drafts7.github.io/knowledgepack_docsify_setup
display_url: https://mail-drafts7.github.io/knowledgepack_docsify_setup

# Editor configuration
editor:
  preview: true

search: true

# Collection definitions
collections:
  - name: "docs"
    label: "📚 Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    extension: "md"
    preview_path: "/{{slug}}"
    fields:
      - { 
          label: "Title", 
          name: "title", 
          widget: "string", 
          required: false
        }
      - { 
          label: "Description", 
          name: "description", 
          widget: "string", 
          required: false
        }
      - { 
          label: "Content", 
          name: "body", 
          widget: "markdown"
        }
        
  # Navigation is now auto-generated from files - no manual management needed
            
  - name: "config"
    label: "⚙️ Site Configuration"
    files:
      - name: "main-readme"
        label: "Main Documentation Page"
        file: "docs/README.md"
        fields:
          - { label: "Content", name: "body", widget: "markdown" }
