# Backend configuration for GitHub
backend:
  name: github
  repo: mail-drafts7/knowledgepack_docsify_setup  # Your GitHub repository
  branch: main                                      # Target branch
  auth_endpoint: api/auth                          # Custom auth endpoint (optional)

# Enable editorial workflow for content review
publish_mode: editorial_workflow

# Media files configuration
media_folder: "docs/assets"           # Where uploaded media files are stored
public_folder: "/assets"             # Public URL path for media files

# Media library configuration (using built-in for better compatibility)
media_library:
  name: uploadcare
  config:
    publicKey: demopublickey

# Local development support
local_backend: true

# Site URLs
site_url: https://mail-drafts7.github.io/knowledgepack_docsify_setup
display_url: https://mail-drafts7.github.io/knowledgepack_docsify_setup

# Logo and branding
logo_url: https://decapcms.org/img/decap.svg

# Editor configuration
editor:
  preview: true

# Search functionality
search: true

# Collection definitions
collections:
  - name: "docs"
    label: "📚 Documentation"
    folder: "docs"
    create: true
    slug: "{{slug}}"
    extension: "md"
    preview_path: "/{{slug}}"
    fields:
      - { 
          label: "Title", 
          name: "title", 
          widget: "string", 
          required: false,
          hint: "Page title (optional - will use filename if not provided)"
        }
      - { 
          label: "Description", 
          name: "description", 
          widget: "string", 
          required: false,
          hint: "Brief description of the page content"
        }
      - { 
          label: "Content", 
          name: "body", 
          widget: "markdown",
          hint: "Main page content in Markdown format"
        }
        
  - name: "navigation"
    label: "🧭 Site Navigation"
    files:
      - name: "sidebar"
        label: "Sidebar Navigation"
        file: "docs/_sidebar.md"
        fields:
          - { 
              label: "Navigation Menu", 
              name: "body", 
              widget: "markdown", 
              hint: "Edit the navigation menu. Use format: - [Page Name](filename.md)" 
            }
            
  - name: "config"
    label: "⚙️ Site Configuration"
    files:
      - name: "main-readme"
        label: "Main Documentation Page"
        file: "docs/README.md"
        fields:
          - { label: "Page Title", name: "title", widget: "string", required: false }
          - { label: "Content", name: "body", widget: "markdown" }
